name: MLOps_Test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.3'
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Install packages and dependencies
          R --silent -e "install.packages(c(\"gbm\", \"e1071"\, \"caret\", \"Rcpp\"))"
          # Install Python packages
          pip install --upgrade pip
          pip install wheel
          pip install PyDrive2==1.6.0 --use-feature=2020-resolver
          # Install DVC
          wget -c https://github.com/iterative/dvc/releases/download/1.7.2/dvc_1.7.2_amd64.deb
          sudo apt install ./dvc_1.7.2_amd64.deb
          # Run DVC
          dvc pull
          Rscript Train.R
          # Write your CML report
          echo "##MODEL METRICS" > report.md
          cat metrics.txt >> report.md
          
          cml-publish Fit.png --md >> report.md